### ISSUE TITLE
How do I compute gaussian radius?

### ISSUE THREAD

**Issue by kikirizki** [sidml/Understanding-Centernet#1]
I try to generate heatmap using an object centered gaussian kernel like the paper does, I uncommented your code 

            # sigma = gaussian_radius(wh)
            # dist_squared = np.sum((self.xy_mesh - center[:, None, None]) ** 2, axis=0)
            # gauss = np.exp(-1 * dist_squared / (2 * sigma ** 2))
            # heatmap[0, :, :] = np.maximum(heatmap[0, :, :], gauss)

but it seem that the `gaussian_radius()` function is not implemented yet. can you point out paper/sources regarding this, please

**Comment by sidml** [comment]
You can use something like this..
```python
def gaussian_radius(bbox_size: Tuple[int, int], min_overlap=0.7):
    width, height = bbox_size

    a1  = 1
    b1  = (height + width)
    c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
    sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
    r1  = (b1 + sq1) / 2

    a2  = 4
    b2  = 2 * (height + width)
    c2  = (1 - min_overlap) * width * height
    sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
    r2  = (b2 + sq2) / 2

    a3  = 4 * min_overlap
    b3  = -2 * min_overlap * (height + width)
    c3  = (min_overlap - 1) * width * height
    sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
    r3  = (b3 + sq3) / 2

    return min(r1, r2, r3)`

**Comment by sidml** [comment]
You may also want to checkout the  [cornernet repo.](https://github.com/princeton-vl/CornerNet/blob/3e71377b45098f9cea26d5a39de0138174c90d49/sample/utils.py)

**Comment by kikirizki** [comment]
Thanks it solve the problem

**Comment by kikirizki** [comment]
The code above known to be have sever bugs, CenterNet code is brought from CornerNet, they have been fix it 
```

def gaussian_radius(det_size, min_overlap):
    height, width = det_size

    a1  = 1
    b1  = (height + width)
    c1  = width * height * (1 - min_overlap) / (1 + min_overlap)
    sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)
    r1  = (b1 - sq1) / (2 * a1)

    a2  = 4
    b2  = 2 * (height + width)
    c2  = (1 - min_overlap) * width * height
    sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)
    r2  = (b2 - sq2) / (2 * a2)

    a3  = 4 * min_overlap
    b3  = -2 * min_overlap * (height + width)
    c3  = (min_overlap - 1) * width * height
    sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)
    r3  = (b3 + sq3) / (2 * a3)
    return min(r1, r2, r3)
```

please refer to https://github.com/princeton-vl/CornerNet/commit/3e71377b45098f9cea26d5a39de0138174c90d49
and 
https://github.com/xingyizhou/CenterNet/issues/273
