### ISSUE TITLE
Not able to understand the significance of indices == 4

### ISSUE THREAD

**Issue by akshathvarugeese** [sidml/Understanding-Centernet#3]
https://github.com/sidml/Understanding-Centernet/blob/c4986ff6401c573393171e82f603140be5f28577/postprocess.py#L29

Hi, I am trying to understand your implementation of CenterNet and extend it for two classes in Keras. But, I am not able to understand the significance of indices == 4 in Line 29 which is a condition in torch.where() method? 

Furthermore, I also had a doubt on Line 37 to Line 40, shouldn't the variable "i_indices" and "j_indices" be swapped when adding to offsets predicted by network because "i_indices" refers to x coordinates and "j_indices" refers to y coordinates in the heatmap? Please correct me if I am wrong. 

https://github.com/sidml/Understanding-Centernet/blob/c4986ff6401c573393171e82f603140be5f28577/postprocess.py#L37

Please clarify my doubts, thanks.

**Comment by sidml** [comment]
Thanks for bringing this up. I don't use [postprocess.py](https://github.com/sidml/Understanding-Centernet/blob/c4986ff6401c573393171e82f603140be5f28577/postprocess.py). I forgot to remove it before committing. I have removed it in the latest commit.

You may want to checkout [ctdet.py](https://github.com/sidml/Understanding-Centernet/blob/c4986ff6401c573393171e82f603140be5f28577/ctdet.py). It performs simiiar functionality.

**Comment by akshathvarugeese** [comment]
Thanks for the quick reply, I had another doubt shouldn't the size also be scaled down with respect to the network stride? 
https://github.com/sidml/Understanding-Centernet/blob/c4986ff6401c573393171e82f603140be5f28577/dataset.py#L50

Shouldn't it be width / 4 and height / 4? In your case diameter / 4.

**Comment by sidml** [comment]
I create circle using cv2.circle function. The smallest bounding box that encloses this circle will have width and height as 2*radius.
